#$Id$

# Makefile for MakeNeXus
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/MakeNeXus/makefile.pro;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/MakeNeXus/make_nexus.sav /SNS/users/j35/IDL/MakeNeXus/

