#$Id$

# Makefile for MFN (MyFirstNexus)
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp makenexus.sav /SNS/software/idltools/sav/
	cp MakeNeXus /SNS/software/idltools/


