# Makefile for SANSreduction
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp sans_reduction.sav /SNS/software/idltools/sav/
	cp SANSreduction /SNS/software/idltools/
	cp images/selection_half_in.bmp /SNS/software/idltools/images/
	cp images/selection_half_out.bmp /SNS/software/idltools/images/
	cp images/selection_inside_in.bmp /SNS/software/idltools/images/
	cp images/selection_inside_out.bmp /SNS/software/idltools/images/
	cp images/selection_outside_in.bmp /SNS/software/idltools/images/
	cp images/selection_outside_out.bmp /SNS/software/idltools/images/
