#$Id$

# Makefile for refl_support
# Compile the necessary modules
# Create the VM program 
all:
	idl ./makefile.pro;

install: 
	cp refl_support.sav /SNS/software/idltools/sav/
	cp RefScale /SNS/software/idltools/


