#!/bin/tcsh

#
# Parse arguments...
#

if ( "#$1#" == '##' ) then
	echo "usage: runmp <fileroot> [-a <alternate_output_path>][-m <mapfile>]"
	exit 0
else
	set fileroot = "$1"
endif

set outputfile = ""
set mapfile    = ""

if ("#$2#" == '#-a#') then 
    set outputfile = "-a $3"
    if ("#$4#" == '#-m#') then 
	set outputfile = "-m $5"
    endif
else 
    if ("#$2#" == '#-m#') then 
	set mapfile = "-m $3"
    endif
endif


#set outputfile = ""
#if ( "#$2#" != '##' ) then 
#	set outputfile = "-a $2"
#endif

#set mapfile = ""
#if ( "#$3#" != '##' ) then
#	set mapfile = "-m $3"
#endif


#
# Parse Runinfo File for Basic Command Parameters...
#
set args = `awk -f ~/SVN/HistoTool/trunk/cli/runinfo.awk ${fileroot}_runinfo.xml`

#
# Generate and Map Polarization Histograms...
#

echo
echo "Running:"
echo
echo "~/SVN/HistoTool/trunk/cli/Event_to_Histo_Mapped " $args $mapfile $outputfile \
	${fileroot}"_neutron_event.dat" $mapfile
echo

~/SVN/HistoTool/trunk/cli/Event_to_Histo_Mapped $args $mapfile ${fileroot}_neutron_event.dat $outputfile

