#$Id$

# Makefile for REFreduction and miniREFreduction
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp bss_selection.sav /SNS/software/idltools/sav/
	cp bss_selection /SNS/software/idltools/


