#$Id$

# Makefile for plotROI application
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp plot_roi.sav /SNS/software/idltools/sav/
	cp plotROI /SNS/software/idltools/

