# Makefile for plotCNCS
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp plot_cncs.sav /SNS/software/idltools/sav/
	cp plotCNCS /SNS/software/idltools/

