# Makefile for realignBSS
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp plot_data.sav /SNS/software/idltools/sav/
	cp plotBSS /SNS/software/idltools/

