# Makefile for DAD
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	cp NeedHelp.cfg .NeedHelp.cfg
	idl ./makefile.pro;
install:
	cp NeedHelp.cfg .NeedHelp.cfg
	cp .NeedHelp.cfg /SNS/software/idltools/sav/
	cp need_help.sav /SNS/software/idltools/sav/
	cp NeedHelp_images/*.png /SNS/software/idltools/sav/NeedHelp_images/
	cp NeedHelp /SNS/software/idltools/
	cp .NeedHelp.cfg /SNS/software5/idltools/sav/
	cp need_help.sav /SNS/software5/idltools/sav/
	cp NeedHelp_images/*.png /SNS/software5/idltools/sav/NeedHelp_images/
	cp NeedHelp /SNS/software5/idltools/


