# Makefile for SNS_offspec
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro

install:
#	cp sans_reduction.sav /SNS/software/idltools/sav/
#	cp mini_sans_reduction.sav /SNS/software/idltools/sav/
#	cp SANSreduction /SNS/software/idltools/
#	cp miniSANSreduction /SNS/software/idltools/

test:
	idl ./make_and_run_test_unit

doc:
	idl ./make_doc.pro