#$Id$

# Makefile for miniReflPak
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/REF/makefile.pro;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/REF/extract_data.sav /SNS/users/j35/IDL/REF/
