#!/bin/bash
# install_SANScalibration.sh
#
# Usage: install_SANScalibration [-d <where to install the software>] 
#                                [-e <path to executable file>]   
#                                [-h]
#
FOLDERS=("SANScalibration_images")
FILES="sans_calibration.sav SANScalibration.cfg mini_sans_calibration.sav"
NBR_PARAMETERS=4   #total number of parameters necessary
EXECUTABLE_SAV="sans_calibration.sav"
MINI_EXECUTABLE_SAV="mini_sans_calibration.sav"
EXECUTABLE='SANScalibration'
MINI_EXECUTABLE='miniSANScalibration'
PACKAGE_PATH='/usr/local/'
EXECUTABLE_PATH='/usr/local/bin/'

#------------------------------------------------------------------------------
help_install()
{
#inform how to use program if user put -h 
   echo "*********************************************************************"
   echo "This is the Help in How to use the SANScalibration installation" 
   echo "program."
   echo "To install the software, do the following:"
   echo
   echo "sudo ./install_SANScalibration [-d <where to intall the software>] "
   echo "                               [-e <path to executable file>] "
   echo "                               [-h]"
   echo
   echo "Examples:"
   echo "  sudo ./install_SANScalibration"
   echo "  sudo ./install_SANScalibration -d ~/usr/local/"
   echo "  sudo ./install_SANScalibration -e ~/bin/"
   echo "  ./install_SANScalibration -d ~/usr/local/ -e ~/usr/local/bin/"
   echo
   exit 1
}

#------------------------------------------------------------------------------
# This function copy the folder(s) to their final location
copy_folders()
{  
    PACKAGE_PATH=$PACKAGE_PATH'/idl/SANScalibration/'
    install -d $PACKAGE_PATH
    for folder in ${FOLDERS[@]}
    do
	echo -n "Copying folder" $folder "to" $PACKAGE_PATH "... "
	cp -rf $folder $PACKAGE_PATH
	echo " Done"
    done
}

#------------------------------------------------------------------------------
# This function copy the file(s) to their final location
copy_files()
{  
    for file in ${FILES[@]}
      do 
      echo -n "Copying file" $file "to" $PACKAGE_PATH "... "	
      cp $file $PACKAGE_PATH
      echo " Done"
    done
}

#------------------------------------------------------------------------------
# This function create the executable file
create_exec()
{
    EXECUTABLE=$EXECUTABLE_PATH"/"$EXECUTABLE
    echo -n "Create executable file" $EXECUTABLE_PATH "...."
    install -d $EXECUTABLE_PATH
    echo "idl -vm=$PACKAGE_PATH/$EXECUTABLE_SAV" > $EXECUTABLE
    echo " Done"
    echo -n "Change permission of $EXECUTABLE to 755 ...."
    chmod 755 $EXECUTABLE
    echo " Done"

    EXECUTABLE=$EXECUTABLE_PATH"/"$MINI_EXECUTABLE
    echo -n "Create executable file" $EXECUTABLE_PATH "...."
    install -d $EXECUTABLE_PATH
    echo "idl -vm=$PACKAGE_PATH/$MINI_EXECUTABLE_SAV" > $EXECUTABLE
    echo " Done"
    echo -n "Change permission of $EXECUTABLE to 755 ...."
    chmod 755 $EXECUTABLE
    echo " Done"
}

#------------------------------------------------------------------------------
#
# Start main procedure
#
if [ $# != 0 ] #not default case
then
    while [ "$1" != "" ] 
    do
	case $1 in
	    -h) 
		help_install;;
		--help)
		help_install;;
	    -d) 
		PACKAGE_PATH=$2;
		shift;;
	    -e) 
		EXECUTABLE_PATH=$2;
		shift;;
	esac
	shift
    done
fi
copy_folders
copy_files
create_exec

