#!/bin/bash
# install_SANSreduction.sh
#
# Usage: install_SANSreduction -d <where to install the software> 
#                              -e <full name of executable file>   
#
#
FOLDERS=("images" "SANSreductionHelp")
FILES="sans_reduction.sav"
NBR_PARAMETERS=4   #total number of parameters necessary
EXECUTABLE="sans_reduction.sav"

#------------------------------------------------------------------------------
help_install()
{
#inform how to use program if user put -h 
   echo "*********************************************************************"
   echo "This is the Help in How to use the SANSreduction installation program"
   echo "To install the software, do the following:"
   echo
   echo "./install_SANSreduction -d <where to intall the software> "
   echo "                        -n <full name of executable file>"
   echo
   echo "Example:"
   echo "       ./install_SANSreduction -d ~/usr/local/ -n ~/bin/mySANSreduction"
   echo
   exit 1
}

#------------------------------------------------------------------------------
# This function creates the new output folder if this one does not exist yet
create_new_folder

#------------------------------------------------------------------------------
# This function copy the folder(s) to their final location
copy_folders()
{  
for folder in $FOLDERS
do
   echo -n "Copying folder" $folder "to" $1 "...."
   install -d $1
   cp -rf $folder $1
   echo " Done"
done
}

#------------------------------------------------------------------------------
# This function copy the file(s) to their final location
copy_files()
{  
for file in $FILES
do 
   echo -n "Copying file" $file "to" $1 "...."	
   cp $file $1
   echo " Done"
done
}

#------------------------------------------------------------------------------
# This function create the executable file
create_exec()
{
echo -n "Create executable file" $2 "...."
echo "idl -vm=$1/$EXECUTABLE" > $2
echo " Done"
echo -n "Change permission of $2 to 755 ...."
chmod 755 $2
echo " Done"
}

#------------------------------------------------------------------------------
#
# Start main procedure
#
if [ $# -ne $NBR_PARAMETERS ] 
    then    #continue only if we have 4 parameters
    help_install
else
    case "$1" in
	"-h") help_install;;
	"-d")
	    create_new_output_folder $2;
	    copy_folders $2;
	    copy_files $2;
	    create_exec $2 $4;;
	"-e")
	    create_new_folder $2;
	    copy_folders $4;
	    copy_files $4;
	    create_exec $4 $2;;
    esac
fi
#------------------------------------------------------------------------------
