#!/bin/bash

Event_to_Histo -l 200 -M 150000 -p 77824 REF_L_2454_neutron_event.dat

echo ""
echo "plus:"
echo ""

Map_Data -p 77824 -m REF_L_TS_2006_12_01.dat \
	-n REF_L_2454_neutron_histo.dat -t 750

