#!/bin/tcsh


#
# Parse arguments...
#

set debug = ""

if ( "#$1#" == '##' ) then
	echo "usage: runmp [-debug] <fileroot> [<mapfile>]"
	exit 0
else
	if ( "#$1#" == '#-debug#' ) then
		set debug = "-d"
		shift
	endif
	set fileroot = "$1"
endif

set mapfile = ""
if ( "#$2#" != '##' ) then
	set mapfile = "-m $2"
endif

#
# Parse Runinfo File for Basic Command Parameters...
#
set args = `awk -f runinfo.awk ${fileroot}_runinfo.xml`

#
# Generate and Map Polarization Histograms...
#

echo
echo "Running:"
echo
echo "Event_to_Histo_Mapped " $debug $args $mapfile \
	${fileroot}"_neutron_event.dat"
echo

Event_to_Histo_Mapped $debug $args $mapfile \
	${fileroot}_neutron_event.dat

