#!/bin/bash
# install_SANSreduction.sh
#
# Usage: install_SANSreduction [-d <where to install the software>] 
#                              [-e <path to executable file>]   
#                              [-h]
#
FOLDERS=("SANSreduction_images" "SANSreductionHelp")
FILES=("sans_reduction.sav" "mini_sans_reduction.sav SANSreduction.cfg")
NBR_PARAMETERS=4   #total number of parameters necessary
EXECUTABLE_SAV="sans_reduction.sav"
EXECUTABLE_MINI_SAV="mini_sans_reduction.sav"
EXECUTABLE='SANSreduction'
EXECUTABLE_MINI='miniSANSreduction'
PACKAGE_PATH='/usr/local/'
EXECUTABLE_PATH='/usr/local/bin/'

#------------------------------------------------------------------------------
help_install()
{
#inform how to use program if user put -h 
   echo "*********************************************************************"
   echo "This is the Help in How to use the SANSreduction installation program"
   echo "To install the software, do the following:"
   echo
   echo "sudo ./install_SANSreduction [-d <where to intall the software>] "
   echo "                             [-e <path to executable file>] "
   echo "                             [-h]"
   echo
   echo "Examples:"
   echo "       sudo ./install_SANSreduction"
   echo "       sudo ./install_SANSreduction -d ~/usr/local/"
   echo "       sudo ./install_SANSreduction -e ~/bin/"
   echo "       ./install_SANSreduction -d ~/usr/local/ -e ~/bin/"
   echo
   exit 1
}

#------------------------------------------------------------------------------
# This function copy the folder(s) to their final location
copy_folders()
{  
    PACKAGE_PATH=$PACKAGE_PATH'/idl/SANSreduction/'
    install -d $PACKAGE_PATH
    for folder in ${FOLDERS[@]}
    do
	echo 'here'
	echo -n "Copying folder" $folder "to" $PACKAGE_PATH "... "
	cp -rf $folder $PACKAGE_PATH
	echo " Done"
    done
}

#------------------------------------------------------------------------------
# This function copy the file(s) to their final location
copy_files()
{  
    for file in ${FILES[@]}
      do 
      echo -n "Copying file" $file "to" $PACKAGE_PATH "... "	
      cp $file $PACKAGE_PATH
      echo " Done"
    done
}

#------------------------------------------------------------------------------
# This function create the executable file
create_exec()
{
    EXECUTABLE1=$EXECUTABLE_PATH"/"$EXECUTABLE_MINI
    echo -n "Create executable file" $EXECUTABLE_PATH "...."
    install -d $EXECUTABLE_PATH
    echo "idl -vm=$PACKAGE_PATH/$EXECUTABLE_MINI_SAV" > $EXECUTABLE1
    echo " Done"
    echo -n "Change permission of $EXECUTABLE1 to 755 ...."
    chmod 755 $EXECUTABLE1

    EXECUTABLE2=$EXECUTABLE_PATH$EXECUTABLE
    echo -n "Create executable file" $EXECUTABLE_PATH "...."
    install -d $EXECUTABLE_PATH
    echo "idl -vm=$PACKAGE_PATH/$EXECUTABLE_SAV" > $EXECUTABLE2
    echo " Done"
    echo -n "Change permission of $EXECUTABLE2 to 755 ...."
    chmod 755 $EXECUTABLE2

    echo " Done"
}

#------------------------------------------------------------------------------
#
# Start main procedure
#
if [ $# != 0 ] #not default case
then
    while [ "$1" != "" ] 
    do
	case $1 in
	    -h) 
		help_install;;
	    -d) 
		PACKAGE_PATH=$2;
		shift;;
	    -e) 
		EXECUTABLE_PATH=$2;
		shift;;
	esac
	shift
    done
fi
copy_folders
copy_files
create_exec

