# Makefile for plotASCII
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	cp plotASCII.cfg .plotASCII.cfg
	idl ./makefile.pro
install:
	cp plot_ascii.sav /SNS/software/idltools/sav/
	cp plotASCII /SNS/software/idltools/
	cp .plotASCII.cfg /SNS/software/idltools/sav/
