#$Id$

# Makefile for refl_support
# Compile the necessary modules
# Create the VM program 
all:
	idl ./makefile.pro;

install: 
	cp john_refl_support.sav /SNS/software/idltools/sav/
	cp JohnRefScale /SNS/software/idltools/


