#$Id$

# Makefile for plotBSS and RealginGUI
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/make_plotBSS.pro;
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/make_RealignGUI.pro;
