#$Id$

# Makefile for plotBSS and RealginGUI
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/make_plotBSS.pro;
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/make_RealignGUI.pro;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/plot_data.sav /SNS/users/j35/IDL/BSS/;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/RealignGUI.sav /SNS/users/j35/IDL/BSS/RealignGUI/;
