#$Id$

# Makefile for GG (Geometry Generator)
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp sans_reduction.sav /SNS/software/idltools/sav/
	cp SANSreduction /SNS/software/idltools/

