#$Id$

# Makefile for data_reduction
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/REFreduction/makefile.pro;


