#$Id$

# Makefile for rebin_nexus
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl ./makefile.pro;
install:
	cp rebin_nexus.sav /SNS/software/idltools/sav/
	cp rebinNeXus /SNS/software/idltools/



