# Makefile for DGSreduction Application

all:
	idl ./makefile.pro;
install-dev:
	cp dgsreduction.sav /SNS/software/idltools/sav/DGSreduction/dev 
install:
	cp dgsreduction.sav /SNS/software/idltools/sav/
	cp DGSreduction /SNS/software/idltools/
