#!/bin/bash
# install_SANScalibration.sh
#
# Usage: install_SANScalibration -d <where to install the software> 
# -e <full name of executable file>   
#
#
FOLDERS="images"
FILES="sans_calibration.sav"
NBR_PARAMETERS=4   #total number of parameters necessary
EXECUTABLE="sans_calibration.sav"

#------------------------------------------------------------------------------
help_install()
{
#inform how to use program if user put -h 
   echo "*************************************************************************"
   echo "This is the Help in How to use the SANScalibration installation program"
   echo "To install the software, do the following:"
   echo
   echo "./install_SANScalibration -d <where to intall the software> "
   echo "                        -n <full name of executable file>"
   echo
   echo "Example:"
   echo "       ./install_SANScalibration -d ~/usr/local/ -n ~/bin/mySANScalibration"
   echo
   exit 1
}

#------------------------------------------------------------------------------
# This function copy the folder(s) to their final location
copy_folders()
{  
for folder in $FOLDERS
do
   echo -n "Copying folder" $folder "to" $1 "...."
   cp -rf $folder $1
   echo " Done"
done
}

#------------------------------------------------------------------------------
# This function copy the file(s) to their final location
copy_files()
{  
for file in $FILES
do 
   echo -n "Copying file" $file "to" $1 "...."	
   cp $file $1
   echo " Done"
done
}

#------------------------------------------------------------------------------
# This function create the executable file
create_exec()
{
echo -n "Create executable file" $2 "...."
echo "idl -vm=$1/$EXECUTABLE" > $2
echo " Done"
echo -n "Change permission of $2 to 755 ...."
chmod 755 $2
echo " Done"
}

#------------------------------------------------------------------------------
#
# Start main procedure
#
if [ $# -ne $NBR_PARAMETERS ] 
then    #continue only if we have 4 parameters
   help_install
else
   case "$1" in
      "-h") help_install;;
      "-d")
     	   copy_folders $2;
     	   copy_files $2;
	   create_exec $2 $4;;
      "-e")
    	   copy_folders $4;
     	   copy_files $4;
	   create_exec $4 $2;;
   esac
fi
#------------------------------------------------------------------------------
