# Makefile for CLoop
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp cloop.sav /SNS/software/idltools/sav/
	cp CLoop /SNS/software/idltools/

