# Makefile Nom
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

# make : builds the executable via the idl virtual machine
# make install : deploys the program as main version into /SNS/NOM/shared/

all:
	idl ./makefile.pro;

install:
	cp idl_bin.sav /SNS/NOM/shared/
	
