# Makefile for iMars
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	cp iMars.cfg .iMars.cfg
	idl ./makefile.pro;
install:
	cp .iMars.cfg /SNS/software/idltools/sav/
	cp iMars.sav /SNS/software/idltools/sav/
	cp iMars /SNS/software/idltools/

