#!/bin/bash

make
make tar

file_name_to_search="SANScalibration.cfg"

application=`./get_application.pl $file_name_to_search`
version=`./get_version.pl $file_name_to_search`

tar_file_name="./"$application"_"$version".tar"

#scp file
scp $tar_file_name bilheuxjm@perun.iucf.indiana.edu:~/test/
