#$Id$

# Makefile for Main IDL interface
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/MainInterface/makefile.pro;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/REF/miniReflPak /SNS/users/j35/IDL/REF/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/REF/extract_data.sav /SNS/users/j35/IDL/REF/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/plot_data.sav /SNS/users/j35/IDL/BSS/;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/RealignGUI.sav /SNS/users/j35/IDL/BSS/RealignGUI/;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/plotBSS /SNS/users/j35/IDL/BSS/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/RealignBSS /SNS/users/j35/IDL/BSS/RealignGUI/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/MakeNeXus/rebin_nexus.sav /SNS/users/j35/IDL/RebinNeXus/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/MakeNeXus/rebinNeXus /SNS/users/j35/IDL/RebinNeXus/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/MainInterface/main_interface.sav /SNS/users/j35/IDL/MainInterface/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/MainInterface/sns_idl_tools /SNS/users/j35/IDL/MainInterface/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/DataReduction/data_reduction.sav /SNS/users/j35/IDL/DataReduction/
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/DataReduction/data_reduction /SNS/users/j35/IDL/DataReduction/

