#$Id$

# Makefile for plotBSS and RealginGUI
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl ./makefile_plotBSS.pro
install:
	cp plot_data.sav /SNS/software/idltools/sav/
	cp plotBSS /SNS/software/idltools/
