#$Id$

# Makefile for plotBSS
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/makefile.pro;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/BSS/plot_data.sav /SNS/users/j35/IDL/BSS/
