# Makefile for plotARCS
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp plot_arcs.sav /SNS/software/idltools/sav/
	cp plotARCS /SNS/software/idltools/

