#$Id$

# Makefile for MFN (MyFirstNexus)
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp mfn.sav /SNS/software/idltools/sav/
	cp MFN /SNS/software/idltools/


