#$Id$

# Makefile for data_reduction
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl ./makefile.pro;

install:
	cp ref_reduction.sav /SNS/software/idltools/sav/
	cp ref_reduction /SNS/software/idltools/

