x# Makefile for REFscale
# Compile the necessary modules
# Create the VM program 
all:
	idl ./makefile.pro;

install: 
	cp ref_scale.sav /SNS/software/idltools/sav/
	cp REFscale /SNS/software/idltools/


