# Makefile for DAD
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	cp DAD.cfg .DAD.cfg
	idl ./makefile.pro;
install:
	cp .DAD.cfg /SNS/software/idltools/sav/
	cp dad.sav /SNS/software/idltools/sav/
	cp DAD /SNS/software/idltools/

