# Makefile for GUIdesigner
# Compile the necessary modules
# Create the VM programs 

all:
	idl ./makefile.pro;
install:
	cp guidesigner.sav /SNS/software/idltools/sav/
	cp GUIdesigner /SNS/software/idltools/

