#$Id$

# Makefile for Main IDL interface
# Compile the necessary modules
# Create the VM program 
# Copy the VM program in its final location

all:
	idl /SNS/users/j35/SVN/HistoTool/trunk/gui/MainInterface/makefile.pro;
	cp /SNS/users/j35/SVN/HistoTool/trunk/gui/MainInterface/main_interface.sav /SNS/users/j35/IDL/MainInterface/
