# Makefile for CLoopES
# Compile the necessary modules
# Create the VM programs 
# Copy the VM programs in their final location

all:
	idl ./makefile.pro;
install:
	cp cloopes.sav /SNS/software/idltools/sav/
	cp CLoopES /SNS/software/idltools/
	cp .cloopes.cfg /SNS/software/idltools/sav/
	cp -r CLoopES_images /SNS/software/idltools/sav/

